# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf9a2de1cace65b07450e247a6c36081f687560b98433f4e2aeed62d608b81c53aa124a574d70fe2cd9b0ae7a2f09cea62a18c8f6c54821498ca06b5b1200f12

test:
  secret_key_base: a1fcb470f27786f22b5b3f6111bad69466d6627757b39cefa3adfa6a0b9185fd878a51ce628226b8db7b34c112e96b0684598aaca01888934ca0e63ff660958a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
